Repository FujimoriGit/AkiraDiary, pull requests merged in 2024-10, with the labels that each got.

#36 [AD1.0] 日記一覧画面の作成_日記リストとフィルター画面を統合
  Macho/Macho.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Macho/MachoFramework/Sources/MachoView/.swiftlint.yml
  Macho/MachoFramework/Sources/MachoView/Common/Extensions/DateFormat_Date+Extension.swift
  Macho/MachoFramework/Sources/MachoView/Dependencies/DiaryListFilterClient.swift
  Macho/MachoFramework/Sources/MachoView/Dependencies/DiaryListItemClient.swift
  Macho/MachoFramework/Sources/MachoView/Resources/Color.xcassets/dialogBackgroundColor.colorset/Contents.json
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/DiaryListFeature.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/DiaryListView.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/Filter/DiaryListFilterFeature.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/Filter/DiaryListFilterView.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/Filter/Entity/DiaryListFilterItem.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/Filter/Entity/DiaryListFilterTarget.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/ViewParts/DiaryListItemFeature.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/ViewParts/DiaryListItemView.swift
  Macho/MachoFramework/Sources/MachoView/Views/RootView.swift
  Macho/MachoFramework/Sources/MachoView/Views/ViewParts/Modifier/View/SwipeActionView.swift
  Macho/MachoFramework/Sources/MachoView/Views/ViewParts/TrackableList.swift
  Macho/MachoFramework/Sources/MachoView/Views/ViewUtilities/Alert/AlertState+Extension.swift
  Macho/MachoFramework/Sources/RealmHelper/Entities/DiaryListFilterEntity.swift
  Macho/MachoFramework/Sources/RealmHelper/RealmModel/RealmAccessor.swift
  Macho/MachoFramework/Tests/MachoFrameworkTests/AppModels/Realm/RealmAccessorTest.swift
  Macho/MachoFramework/Tests/MachoFrameworkTests/Views/DiaryList/DiaryListViewTest.swift
  Macho/MachoFramework/Tests/MachoFrameworkTests/Views/DiaryList/Filter/DiaryListFilterViewTest.swift
Labels: AD1.0

#41 [AD1.0] 日記一覧画面の作成_TCA1.6から1.12へのマイグレーション対応
  Macho/Macho.xcworkspace/contents.xcworkspacedata
  Macho/Macho.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Macho/MachoFramework/.swiftpm/xcode/xcshareddata/xcschemes/MachoFramework.xcscheme
  Macho/MachoFramework/MachoFramework.xctestplan
  Macho/MachoFramework/Sources/MachoView/Common/Extensions/DateFormat_Date+Extension.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/DiaryListFeature.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/DiaryListView.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/Filter/DiaryListFilterFeature.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/Filter/DiaryListFilterView.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/ViewParts/DiaryListItemFeature.swift
  Macho/MachoFramework/Sources/MachoView/Views/DiaryList/ViewParts/DiaryListItemView.swift
  Macho/MachoFramework/Sources/MachoView/Views/TCASample/Contacts/AddContact/AddContactFeature.swift
  Macho/MachoFramework/Sources/MachoView/Views/TCASample/Contacts/AddContact/AddContactView.swift
  Macho/MachoFramework/Sources/MachoView/Views/TCASample/Contacts/ContactDetail/ContactDetailFeature.swift
  Macho/MachoFramework/Sources/MachoView/Views/TCASample/Contacts/ContactDetail/ContactDetailView.swift
  Macho/MachoFramework/Sources/MachoView/Views/TCASample/Contacts/ContactsFeature.swift
  Macho/MachoFramework/Sources/MachoView/Views/TCASample/Contacts/ContactsView.swift
  Macho/MachoFramework/Sources/MachoView/Views/TCASample/Counter/CounterFeature.swift
  Macho/MachoFramework/Sources/MachoView/Views/TCASample/Counter/CounterView.swift
  Macho/MachoFramework/Sources/RealmHelper/RealmModel/RealmAccessor.swift
  Macho/MachoFramework/Tests/MachoFrameworkTests/Views/DiaryList/DiaryListViewTest.swift
Labels: AD1.0

#43 [1.0] RealmAccessorのprotocolを追加
  .gitignore
  Gemfile.lock
  Macho/Macho.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Macho/MachoFramework/Package.resolved
  Macho/MachoFramework/Sources/RealmHelper/RealmHelper.swift
  Macho/MachoFramework/Sources/RealmHelper/RealmModel/RealmAccessible.swift
  Macho/MachoFramework/Sources/RealmHelper/RealmModel/RealmAccessor.swift
Labels: AD1.0

#45 [AD1.0][GitHub Actions] workflowの修正
  .github/workflows/checkBuild_Test_Swift.yml
  .gitignore
  Gemfile.lock
  Macho/Macho.xcworkspace/xcshareddata/swiftpm/Package.resolved
  wiki/tech/GitActions/Build_Test/README.md
  wiki/tech/GitActions/README.md
Labels: AD1.0, CI / CD

#49 [AD1.0] トレーニング内容のRealm情報修正
  Macho/MachoFramework/Sources/MachoCore/Logger/AppLogger.swift
  Macho/MachoFramework/Sources/MachoView/Common/MachoViewLogger.swift
  Macho/MachoFramework/Sources/RealmHelper/Common/RealmHelperLogger.swift
  Macho/MachoFramework/Sources/RealmHelper/Entities/DiaryEntity.swift
  Macho/MachoFramework/Sources/RealmHelper/Entities/TrainingContentEntity.swift
  Macho/MachoFramework/Sources/RealmHelper/Entities/TrainingGoalEntity.swift
  Macho/MachoFramework/Sources/RealmHelper/Entities/TrainingTypeEntity.swift
  Macho/MachoFramework/Sources/RealmHelper/RealmModel/RealmAccessor.swift
  Macho/MachoFramework/Tests/MachoFrameworkTests/AppModels/Realm/RealmAccessorTest.swift
Labels: bug, AD1.0
